version: "2"
services:
  membersrvc:
    build:
      context: membersrvc
    command: membersrvc
    ports:
      - "7054:7054"
  vp0:
    image: hyperledger/fabric-peer:latest
    command: "sh -c 'while ! nc membersrvc 7054; do sleep 1; done; peer node start'"
    environment:
      - CORE_PEER_ADDRESSAUTODETECT=true
      - "CORE_VM_ENDPOINT=unix:///var/run/docker.sock"
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=vp0
      - "CORE_PEER_PKI_ECA_PADDR=membersrvc:7054"
      - "CORE_PEER_PKI_TCA_PADDR=membersrvc:7054"
      - "CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054"
      - CORE_SECURITY_ENABLED=true
      - CORE_SECURITY_ENROLLID=test_vp0
      - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
    links:
      - membersrvc
    ports:
      - "7050:7050"
      - "7051:7051"
      - "7052:7052"
      - "7053:7053"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  car-lease-demo:
    build:
      context: "."
    links:
      - vp0
      - membersrvc
    ports:
      - "8080:8080"
