FROM hyperledger/fabric-peer:latest
# Install required prereqs.
RUN apt-get -y update && apt-get -y install net-tools netcat nmap
# COPY vehicle_code/vehicles.go ./vehicle_code/vehicles.go
# RUN go build ./vehicle_code/vehicles.go
